version: "3"
services:
  soketi:
    image: quay.io/soketi/soketi:latest-16-alpine
    volumes:
        - './config.json:/opt/config.json'
    command: ["node", "/app/bin/server.js", "start", "--config=/opt/config.json"]
    container_name: soketi
    restart: unless-stopped
    tty: true

#Volumes
volumes:
  dbdata:
    driver: local